/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DecentralizedForumInterface extends Interface {
    getFunction(nameOrSignature: "MODERATOR_RECOMMENDATIONS_REQUIRED" | "POST_ACTIVITY_POINTS" | "USERNAME_CHANGE_FEE" | "USERNAME_MAX_LENGTH" | "USERNAME_MIN_LENGTH" | "acceptModeratorRole" | "activityScore" | "addComment" | "approvePendingComment" | "approvePendingPost" | "approveRemoveModeratorProposal" | "banUser" | "batchCreatePosts" | "changeUsername" | "commentHidden" | "communityOfPost" | "createCommunity" | "createFlaggedPost" | "createPost" | "createSubCommunity" | "declineModeratorRole" | "getAddressByUsername" | "getAllCommunityIds" | "getCommentsMerkleRoot" | "getCommunity" | "getCommunityCount" | "getCommunityV2" | "getKnownUsersByCommunity" | "getModeratorAddresses" | "getModeratorCount" | "getModeratorRecommendationStatus" | "getModeratorRole" | "getPendingComment" | "getPendingCommentsByPost" | "getPost" | "getPostCount" | "getPostsByCommunity" | "getRemovalProposalsByCommunity" | "getRemoveModeratorProposal" | "getRequiredRemovalApprovals" | "getSubCommunities" | "getTopActiveUsers" | "getUserJoinedAt" | "getUsername" | "hasApprovedRemoveModeratorProposal" | "hasPendingModeratorOffer" | "hasRecommendedModerator" | "hideComment" | "hidePost" | "isBanned" | "isMember" | "isPostHidden" | "isUserBannedFromCommunity" | "isUserMemberOfCommunity" | "isUserModeratorOfCommunity" | "isUsernameAvailable" | "joinCommunity" | "joinedAt" | "leaveCommunity" | "lockPost" | "postLocked" | "postPendingReview" | "postRejected" | "postScore" | "postVotes" | "proposeRemoveModerator" | "recommendModerator" | "registerUsername" | "rejectPendingComment" | "rejectPendingPost" | "reportComment" | "reportPost" | "resignModerator" | "restorePost" | "submitFlaggedComment" | "unbanUser" | "unlockPost" | "updateCommentsMerkleRoot" | "updateCommunityMetadata" | "userCommunityCount" | "userPostCount" | "votePost"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActiveModeratorsUpdated" | "CommentCreated" | "CommentHidden" | "CommentSubmittedForReview" | "CommentsMerkleRootUpdated" | "CommunityCreated" | "CommunityJoined" | "CommunityLeft" | "CommunityMetadataUpdated" | "ContentReported" | "ModeratorAdded" | "ModeratorOfferAccepted" | "ModeratorOfferCreated" | "ModeratorOfferDeclined" | "ModeratorRecommended" | "ModeratorRemoved" | "ModeratorResigned" | "PendingCommentApproved" | "PendingCommentRejected" | "PendingPostApproved" | "PendingPostRejected" | "PostCreated" | "PostHidden" | "PostLocked" | "PostRestored" | "PostSubmittedForReview" | "PostUnlocked" | "PostVoted" | "RemoveModeratorProposalApproved" | "RemoveModeratorProposalCreated" | "RemoveModeratorProposalExecuted" | "SubCommunityCreated" | "UserBanned" | "UserUnbanned" | "UsernameChanged" | "UsernameRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'MODERATOR_RECOMMENDATIONS_REQUIRED', values?: undefined): string;
encodeFunctionData(functionFragment: 'POST_ACTIVITY_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'USERNAME_CHANGE_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'USERNAME_MAX_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'USERNAME_MIN_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptModeratorRole', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'activityScore', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'addComment', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'approvePendingComment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approvePendingPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveRemoveModeratorProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'banUser', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'batchCreatePosts', values: [BigNumberish, string[], string[], string[]]): string;
encodeFunctionData(functionFragment: 'changeUsername', values: [string]): string;
encodeFunctionData(functionFragment: 'commentHidden', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'communityOfPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createCommunity', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'createFlaggedPost', values: [BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'createPost', values: [BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'createSubCommunity', values: [BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'declineModeratorRole', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAddressByUsername', values: [string]): string;
encodeFunctionData(functionFragment: 'getAllCommunityIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCommentsMerkleRoot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommunityCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCommunityV2', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getKnownUsersByCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getModeratorAddresses', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getModeratorCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getModeratorRecommendationStatus', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getModeratorRole', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getPendingComment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPendingCommentsByPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPostCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPostsByCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRemovalProposalsByCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRemoveModeratorProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRequiredRemovalApprovals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSubCommunities', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTopActiveUsers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserJoinedAt', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getUsername', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasApprovedRemoveModeratorProposal', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasPendingModeratorOffer', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRecommendedModerator', values: [BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hideComment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hidePost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isBanned', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isMember', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isPostHidden', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isUserBannedFromCommunity', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isUserMemberOfCommunity', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isUserModeratorOfCommunity', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isUsernameAvailable', values: [string]): string;
encodeFunctionData(functionFragment: 'joinCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'joinedAt', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'leaveCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postLocked', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postPendingReview', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postRejected', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postScore', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postVotes', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'proposeRemoveModerator', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'recommendModerator', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'registerUsername', values: [string]): string;
encodeFunctionData(functionFragment: 'rejectPendingComment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectPendingPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reportComment', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'reportPost', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'resignModerator', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'restorePost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitFlaggedComment', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'unbanUser', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'unlockPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateCommentsMerkleRoot', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'updateCommunityMetadata', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'userCommunityCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userPostCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'votePost', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MODERATOR_RECOMMENDATIONS_REQUIRED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'POST_ACTIVITY_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USERNAME_CHANGE_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USERNAME_MAX_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USERNAME_MIN_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptModeratorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activityScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approvePendingComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approvePendingPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveRemoveModeratorProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'banUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchCreatePosts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changeUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commentHidden', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'communityOfPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createFlaggedPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createSubCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'declineModeratorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAddressByUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCommunityIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommentsMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommunityCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommunityV2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getKnownUsersByCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModeratorAddresses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModeratorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModeratorRecommendationStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getModeratorRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingCommentsByPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPostCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPostsByCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemovalProposalsByCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemoveModeratorProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequiredRemovalApprovals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubCommunities', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTopActiveUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserJoinedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasApprovedRemoveModeratorProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasPendingModeratorOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRecommendedModerator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hideComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hidePost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBanned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPostHidden', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUserBannedFromCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUserMemberOfCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUserModeratorOfCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUsernameAvailable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leaveCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postPendingReview', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postRejected', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeRemoveModerator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recommendModerator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerUsername', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectPendingComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectPendingPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resignModerator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'restorePost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitFlaggedComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbanUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCommentsMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCommunityMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userCommunityCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userPostCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votePost', data: BytesLike): Result;
  }

  
    export namespace ActiveModeratorsUpdatedEvent {
      export type InputTuple = [communityId: BigNumberish, firstActiveModerator: AddressLike, secondActiveModerator: AddressLike, updatedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, firstActiveModerator: string, secondActiveModerator: string, updatedAt: bigint];
      export interface OutputObject {communityId: bigint, firstActiveModerator: string, secondActiveModerator: string, updatedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommentCreatedEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, communityId: BigNumberish, author: AddressLike, content: string, imageCid: string, createdAt: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, communityId: bigint, author: string, content: string, imageCid: string, createdAt: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, communityId: bigint, author: string, content: string, imageCid: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommentHiddenEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, communityId: BigNumberish, hiddenBy: AddressLike, hiddenAt: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, communityId: bigint, hiddenBy: string, hiddenAt: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, communityId: bigint, hiddenBy: string, hiddenAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommentSubmittedForReviewEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, communityId: BigNumberish, author: AddressLike, content: string, imageCid: string, submittedAt: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, communityId: bigint, author: string, content: string, imageCid: string, submittedAt: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, communityId: bigint, author: string, content: string, imageCid: string, submittedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommentsMerkleRootUpdatedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, commentsMerkleRoot: BytesLike, updatedBy: AddressLike, updatedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, commentsMerkleRoot: string, updatedBy: string, updatedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, commentsMerkleRoot: string, updatedBy: string, updatedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityCreatedEvent {
      export type InputTuple = [communityId: BigNumberish, creator: AddressLike, name: string, metadataCID: string, description: string, createdAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, creator: string, name: string, metadataCID: string, description: string, createdAt: bigint];
      export interface OutputObject {communityId: bigint, creator: string, name: string, metadataCID: string, description: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityJoinedEvent {
      export type InputTuple = [communityId: BigNumberish, member: AddressLike, joinedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, member: string, joinedAt: bigint];
      export interface OutputObject {communityId: bigint, member: string, joinedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityLeftEvent {
      export type InputTuple = [communityId: BigNumberish, member: AddressLike, leftAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, member: string, leftAt: bigint];
      export interface OutputObject {communityId: bigint, member: string, leftAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityMetadataUpdatedEvent {
      export type InputTuple = [communityId: BigNumberish, metadataCID: string, updatedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, metadataCID: string, updatedAt: bigint];
      export interface OutputObject {communityId: bigint, metadataCID: string, updatedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContentReportedEvent {
      export type InputTuple = [refId: BigNumberish, communityId: BigNumberish, kind: BigNumberish, reporter: AddressLike, reason: string, reportedAt: BigNumberish];
      export type OutputTuple = [refId: bigint, communityId: bigint, kind: bigint, reporter: string, reason: string, reportedAt: bigint];
      export interface OutputObject {refId: bigint, communityId: bigint, kind: bigint, reporter: string, reason: string, reportedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorAddedEvent {
      export type InputTuple = [communityId: BigNumberish, moderator: AddressLike, addedBy: AddressLike, addedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, moderator: string, addedBy: string, addedAt: bigint];
      export interface OutputObject {communityId: bigint, moderator: string, addedBy: string, addedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorOfferAcceptedEvent {
      export type InputTuple = [communityId: BigNumberish, candidate: AddressLike, acceptedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, candidate: string, acceptedAt: bigint];
      export interface OutputObject {communityId: bigint, candidate: string, acceptedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorOfferCreatedEvent {
      export type InputTuple = [communityId: BigNumberish, candidate: AddressLike, createdAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, candidate: string, createdAt: bigint];
      export interface OutputObject {communityId: bigint, candidate: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorOfferDeclinedEvent {
      export type InputTuple = [communityId: BigNumberish, candidate: AddressLike, declinedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, candidate: string, declinedAt: bigint];
      export interface OutputObject {communityId: bigint, candidate: string, declinedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorRecommendedEvent {
      export type InputTuple = [communityId: BigNumberish, candidate: AddressLike, recommender: AddressLike, recommendations: BigNumberish, recommendedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, candidate: string, recommender: string, recommendations: bigint, recommendedAt: bigint];
      export interface OutputObject {communityId: bigint, candidate: string, recommender: string, recommendations: bigint, recommendedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorRemovedEvent {
      export type InputTuple = [communityId: BigNumberish, moderator: AddressLike, removedBy: AddressLike, removedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, moderator: string, removedBy: string, removedAt: bigint];
      export interface OutputObject {communityId: bigint, moderator: string, removedBy: string, removedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ModeratorResignedEvent {
      export type InputTuple = [communityId: BigNumberish, moderator: AddressLike, resignedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, moderator: string, resignedAt: bigint];
      export interface OutputObject {communityId: bigint, moderator: string, resignedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PendingCommentApprovedEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, communityId: BigNumberish, moderator: AddressLike, approvedAt: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, communityId: bigint, moderator: string, approvedAt: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, communityId: bigint, moderator: string, approvedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PendingCommentRejectedEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, communityId: BigNumberish, moderator: AddressLike, rejectedAt: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, communityId: bigint, moderator: string, rejectedAt: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, communityId: bigint, moderator: string, rejectedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PendingPostApprovedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, moderator: AddressLike, approvedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, moderator: string, approvedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, moderator: string, approvedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PendingPostRejectedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, moderator: AddressLike, rejectedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, moderator: string, rejectedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, moderator: string, rejectedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostCreatedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, author: AddressLike, contentCID: string, title: string, tags: string, createdAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, author: string, contentCID: string, title: string, tags: string, createdAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, author: string, contentCID: string, title: string, tags: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostHiddenEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, hiddenBy: AddressLike, hiddenAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, hiddenBy: string, hiddenAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, hiddenBy: string, hiddenAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostLockedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, lockedBy: AddressLike, lockedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, lockedBy: string, lockedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, lockedBy: string, lockedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostRestoredEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, restoredBy: AddressLike, restoredAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, restoredBy: string, restoredAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, restoredBy: string, restoredAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostSubmittedForReviewEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, author: AddressLike, title: string, submittedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, author: string, title: string, submittedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, author: string, title: string, submittedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostUnlockedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, unlockedBy: AddressLike, unlockedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, unlockedBy: string, unlockedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, unlockedBy: string, unlockedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostVotedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, voter: AddressLike, vote: BigNumberish, newScore: BigNumberish, votedAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, voter: string, vote: bigint, newScore: bigint, votedAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, voter: string, vote: bigint, newScore: bigint, votedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveModeratorProposalApprovedEvent {
      export type InputTuple = [proposalId: BigNumberish, communityId: BigNumberish, approver: AddressLike, approvals: BigNumberish, approvedAt: BigNumberish];
      export type OutputTuple = [proposalId: bigint, communityId: bigint, approver: string, approvals: bigint, approvedAt: bigint];
      export interface OutputObject {proposalId: bigint, communityId: bigint, approver: string, approvals: bigint, approvedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveModeratorProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, communityId: BigNumberish, target: AddressLike, proposer: AddressLike, approvals: BigNumberish, createdAt: BigNumberish];
      export type OutputTuple = [proposalId: bigint, communityId: bigint, target: string, proposer: string, approvals: bigint, createdAt: bigint];
      export interface OutputObject {proposalId: bigint, communityId: bigint, target: string, proposer: string, approvals: bigint, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveModeratorProposalExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish, communityId: BigNumberish, target: AddressLike, executedAt: BigNumberish];
      export type OutputTuple = [proposalId: bigint, communityId: bigint, target: string, executedAt: bigint];
      export interface OutputObject {proposalId: bigint, communityId: bigint, target: string, executedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubCommunityCreatedEvent {
      export type InputTuple = [communityId: BigNumberish, parentCommunityId: BigNumberish, creator: AddressLike, name: string, metadataCID: string, description: string, createdAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, parentCommunityId: bigint, creator: string, name: string, metadataCID: string, description: string, createdAt: bigint];
      export interface OutputObject {communityId: bigint, parentCommunityId: bigint, creator: string, name: string, metadataCID: string, description: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserBannedEvent {
      export type InputTuple = [communityId: BigNumberish, user: AddressLike, bannedBy: AddressLike, bannedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, user: string, bannedBy: string, bannedAt: bigint];
      export interface OutputObject {communityId: bigint, user: string, bannedBy: string, bannedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserUnbannedEvent {
      export type InputTuple = [communityId: BigNumberish, user: AddressLike, unbannedBy: AddressLike, unbannedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, user: string, unbannedBy: string, unbannedAt: bigint];
      export interface OutputObject {communityId: bigint, user: string, unbannedBy: string, unbannedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsernameChangedEvent {
      export type InputTuple = [user: AddressLike, oldUsername: string, newUsername: string, changedAt: BigNumberish];
      export type OutputTuple = [user: string, oldUsername: string, newUsername: string, changedAt: bigint];
      export interface OutputObject {user: string, oldUsername: string, newUsername: string, changedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsernameRegisteredEvent {
      export type InputTuple = [user: AddressLike, username: string, registeredAt: BigNumberish];
      export type OutputTuple = [user: string, username: string, registeredAt: bigint];
      export interface OutputObject {user: string, username: string, registeredAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DecentralizedForum extends BaseContract {
    
    connect(runner?: ContractRunner | null): DecentralizedForum;
    waitForDeployment(): Promise<this>;

    interface: DecentralizedForumInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MODERATOR_RECOMMENDATIONS_REQUIRED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    POST_ACTIVITY_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    USERNAME_CHANGE_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    USERNAME_MAX_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    USERNAME_MIN_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptModeratorRole: TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    activityScore: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    addComment: TypedContractMethod<
      [postId: BigNumberish, content: string, imageCid: string, ],
      [void],
      'nonpayable'
    >
    

    
    approvePendingComment: TypedContractMethod<
      [commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approvePendingPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveRemoveModeratorProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    banUser: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    batchCreatePosts: TypedContractMethod<
      [communityId: BigNumberish, contentCIDs: string[], titles: string[], tagsList: string[], ],
      [void],
      'nonpayable'
    >
    

    
    changeUsername: TypedContractMethod<
      [newUsername: string, ],
      [void],
      'payable'
    >
    

    
    commentHidden: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    communityOfPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createCommunity: TypedContractMethod<
      [name: string, metadataCID: string, description: string, ],
      [void],
      'nonpayable'
    >
    

    
    createFlaggedPost: TypedContractMethod<
      [communityId: BigNumberish, contentCID: string, title: string, tags: string, ],
      [void],
      'nonpayable'
    >
    

    
    createPost: TypedContractMethod<
      [communityId: BigNumberish, contentCID: string, title: string, tags: string, ],
      [void],
      'nonpayable'
    >
    

    
    createSubCommunity: TypedContractMethod<
      [parentCommunityId: BigNumberish, name: string, metadataCID: string, description: string, ],
      [void],
      'nonpayable'
    >
    

    
    declineModeratorRole: TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAddressByUsername: TypedContractMethod<
      [username: string, ],
      [string],
      'view'
    >
    

    
    getAllCommunityIds: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getCommentsMerkleRoot: TypedContractMethod<
      [postId: BigNumberish, ],
      [[string, bigint] & {root: string, updatedAt: bigint }],
      'view'
    >
    

    
    getCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean] & {id: bigint, name: string, creator: string, metadataCID: string, createdAt: bigint, membersCount: bigint, exists: boolean }],
      'view'
    >
    

    
    getCommunityCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCommunityV2: TypedContractMethod<
      [communityId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean, bigint] & {id: bigint, name: string, creator: string, metadataCID: string, createdAt: bigint, membersCount: bigint, exists: boolean, parentCommunityId: bigint }],
      'view'
    >
    

    
    getKnownUsersByCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getModeratorAddresses: TypedContractMethod<
      [communityId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getModeratorCount: TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getModeratorRecommendationStatus: TypedContractMethod<
      [communityId: BigNumberish, candidate: AddressLike, ],
      [[bigint, bigint, boolean] & {recommendations: bigint, required: bigint, offerPending: boolean }],
      'view'
    >
    

    
    getModeratorRole: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [[boolean, boolean, boolean, boolean] & {isModerator: boolean, isCreatorModerator: boolean, isActiveBasedModerator: boolean, isAppointedModerator: boolean }],
      'view'
    >
    

    
    getPendingComment: TypedContractMethod<
      [commentId: BigNumberish, ],
      [[bigint, bigint, string, string, string, bigint, bigint] & {id: bigint, postId: bigint, author: string, content: string, imageCid: string, createdAt: bigint, status: bigint }],
      'view'
    >
    

    
    getPendingCommentsByPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean, boolean] & {id: bigint, communityId: bigint, author: string, contentCID: string, createdAt: bigint, exists: boolean, hidden: boolean }],
      'view'
    >
    

    
    getPostCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPostsByCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getRemovalProposalsByCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getRemoveModeratorProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean, boolean] & {id: bigint, communityId: bigint, target: string, proposer: string, approvals: bigint, executed: boolean, exists: boolean }],
      'view'
    >
    

    
    getRequiredRemovalApprovals: TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getSubCommunities: TypedContractMethod<
      [parentCommunityId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getTopActiveUsers: TypedContractMethod<
      [communityId: BigNumberish, ],
      [[string, string] & {first: string, second: string }],
      'view'
    >
    

    
    getUserJoinedAt: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUsername: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    hasApprovedRemoveModeratorProposal: TypedContractMethod<
      [proposalId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasPendingModeratorOffer: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasRecommendedModerator: TypedContractMethod<
      [communityId: BigNumberish, candidate: AddressLike, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hideComment: TypedContractMethod<
      [commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    hidePost: TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isBanned: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isMember: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isPostHidden: TypedContractMethod<
      [postId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isUserBannedFromCommunity: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUserMemberOfCommunity: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUserModeratorOfCommunity: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUsernameAvailable: TypedContractMethod<
      [username: string, ],
      [boolean],
      'view'
    >
    

    
    joinCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    joinedAt: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    leaveCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    lockPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    postLocked: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    postPendingReview: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    postRejected: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    postScore: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    postVotes: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    proposeRemoveModerator: TypedContractMethod<
      [communityId: BigNumberish, target: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    recommendModerator: TypedContractMethod<
      [communityId: BigNumberish, candidate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerUsername: TypedContractMethod<
      [username: string, ],
      [void],
      'nonpayable'
    >
    

    
    rejectPendingComment: TypedContractMethod<
      [commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectPendingPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reportComment: TypedContractMethod<
      [commentId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    reportPost: TypedContractMethod<
      [postId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    resignModerator: TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    restorePost: TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitFlaggedComment: TypedContractMethod<
      [postId: BigNumberish, content: string, imageCid: string, ],
      [void],
      'nonpayable'
    >
    

    
    unbanUser: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unlockPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateCommentsMerkleRoot: TypedContractMethod<
      [postId: BigNumberish, commentsMerkleRoot: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateCommunityMetadata: TypedContractMethod<
      [communityId: BigNumberish, metadataCID: string, ],
      [void],
      'nonpayable'
    >
    

    
    userCommunityCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    userPostCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    votePost: TypedContractMethod<
      [postId: BigNumberish, vote: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MODERATOR_RECOMMENDATIONS_REQUIRED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'POST_ACTIVITY_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'USERNAME_CHANGE_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'USERNAME_MAX_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'USERNAME_MIN_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptModeratorRole'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'activityScore'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addComment'): TypedContractMethod<
      [postId: BigNumberish, content: string, imageCid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approvePendingComment'): TypedContractMethod<
      [commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approvePendingPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveRemoveModeratorProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'banUser'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'batchCreatePosts'): TypedContractMethod<
      [communityId: BigNumberish, contentCIDs: string[], titles: string[], tagsList: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'changeUsername'): TypedContractMethod<
      [newUsername: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'commentHidden'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'communityOfPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCommunity'): TypedContractMethod<
      [name: string, metadataCID: string, description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createFlaggedPost'): TypedContractMethod<
      [communityId: BigNumberish, contentCID: string, title: string, tags: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPost'): TypedContractMethod<
      [communityId: BigNumberish, contentCID: string, title: string, tags: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createSubCommunity'): TypedContractMethod<
      [parentCommunityId: BigNumberish, name: string, metadataCID: string, description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'declineModeratorRole'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAddressByUsername'): TypedContractMethod<
      [username: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllCommunityIds'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCommentsMerkleRoot'): TypedContractMethod<
      [postId: BigNumberish, ],
      [[string, bigint] & {root: string, updatedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean] & {id: bigint, name: string, creator: string, metadataCID: string, createdAt: bigint, membersCount: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getCommunityCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCommunityV2'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean, bigint] & {id: bigint, name: string, creator: string, metadataCID: string, createdAt: bigint, membersCount: bigint, exists: boolean, parentCommunityId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getKnownUsersByCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getModeratorAddresses'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getModeratorCount'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getModeratorRecommendationStatus'): TypedContractMethod<
      [communityId: BigNumberish, candidate: AddressLike, ],
      [[bigint, bigint, boolean] & {recommendations: bigint, required: bigint, offerPending: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getModeratorRole'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [[boolean, boolean, boolean, boolean] & {isModerator: boolean, isCreatorModerator: boolean, isActiveBasedModerator: boolean, isAppointedModerator: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingComment'): TypedContractMethod<
      [commentId: BigNumberish, ],
      [[bigint, bigint, string, string, string, bigint, bigint] & {id: bigint, postId: bigint, author: string, content: string, imageCid: string, createdAt: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingCommentsByPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean, boolean] & {id: bigint, communityId: bigint, author: string, contentCID: string, createdAt: bigint, exists: boolean, hidden: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getPostCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPostsByCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRemovalProposalsByCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRemoveModeratorProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean, boolean] & {id: bigint, communityId: bigint, target: string, proposer: string, approvals: bigint, executed: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getRequiredRemovalApprovals'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSubCommunities'): TypedContractMethod<
      [parentCommunityId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTopActiveUsers'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [[string, string] & {first: string, second: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserJoinedAt'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUsername'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasApprovedRemoveModeratorProposal'): TypedContractMethod<
      [proposalId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasPendingModeratorOffer'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasRecommendedModerator'): TypedContractMethod<
      [communityId: BigNumberish, candidate: AddressLike, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hideComment'): TypedContractMethod<
      [commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hidePost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isBanned'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isMember'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPostHidden'): TypedContractMethod<
      [postId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUserBannedFromCommunity'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUserMemberOfCommunity'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUserModeratorOfCommunity'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUsernameAvailable'): TypedContractMethod<
      [username: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'joinCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'joinedAt'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'leaveCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'postLocked'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'postPendingReview'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'postRejected'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'postScore'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'postVotes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposeRemoveModerator'): TypedContractMethod<
      [communityId: BigNumberish, target: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recommendModerator'): TypedContractMethod<
      [communityId: BigNumberish, candidate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerUsername'): TypedContractMethod<
      [username: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectPendingComment'): TypedContractMethod<
      [commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectPendingPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportComment'): TypedContractMethod<
      [commentId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportPost'): TypedContractMethod<
      [postId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resignModerator'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'restorePost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitFlaggedComment'): TypedContractMethod<
      [postId: BigNumberish, content: string, imageCid: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unbanUser'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlockPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCommentsMerkleRoot'): TypedContractMethod<
      [postId: BigNumberish, commentsMerkleRoot: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCommunityMetadata'): TypedContractMethod<
      [communityId: BigNumberish, metadataCID: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userCommunityCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userPostCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'votePost'): TypedContractMethod<
      [postId: BigNumberish, vote: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ActiveModeratorsUpdated'): TypedContractEvent<ActiveModeratorsUpdatedEvent.InputTuple, ActiveModeratorsUpdatedEvent.OutputTuple, ActiveModeratorsUpdatedEvent.OutputObject>;
getEvent(key: 'CommentCreated'): TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
getEvent(key: 'CommentHidden'): TypedContractEvent<CommentHiddenEvent.InputTuple, CommentHiddenEvent.OutputTuple, CommentHiddenEvent.OutputObject>;
getEvent(key: 'CommentSubmittedForReview'): TypedContractEvent<CommentSubmittedForReviewEvent.InputTuple, CommentSubmittedForReviewEvent.OutputTuple, CommentSubmittedForReviewEvent.OutputObject>;
getEvent(key: 'CommentsMerkleRootUpdated'): TypedContractEvent<CommentsMerkleRootUpdatedEvent.InputTuple, CommentsMerkleRootUpdatedEvent.OutputTuple, CommentsMerkleRootUpdatedEvent.OutputObject>;
getEvent(key: 'CommunityCreated'): TypedContractEvent<CommunityCreatedEvent.InputTuple, CommunityCreatedEvent.OutputTuple, CommunityCreatedEvent.OutputObject>;
getEvent(key: 'CommunityJoined'): TypedContractEvent<CommunityJoinedEvent.InputTuple, CommunityJoinedEvent.OutputTuple, CommunityJoinedEvent.OutputObject>;
getEvent(key: 'CommunityLeft'): TypedContractEvent<CommunityLeftEvent.InputTuple, CommunityLeftEvent.OutputTuple, CommunityLeftEvent.OutputObject>;
getEvent(key: 'CommunityMetadataUpdated'): TypedContractEvent<CommunityMetadataUpdatedEvent.InputTuple, CommunityMetadataUpdatedEvent.OutputTuple, CommunityMetadataUpdatedEvent.OutputObject>;
getEvent(key: 'ContentReported'): TypedContractEvent<ContentReportedEvent.InputTuple, ContentReportedEvent.OutputTuple, ContentReportedEvent.OutputObject>;
getEvent(key: 'ModeratorAdded'): TypedContractEvent<ModeratorAddedEvent.InputTuple, ModeratorAddedEvent.OutputTuple, ModeratorAddedEvent.OutputObject>;
getEvent(key: 'ModeratorOfferAccepted'): TypedContractEvent<ModeratorOfferAcceptedEvent.InputTuple, ModeratorOfferAcceptedEvent.OutputTuple, ModeratorOfferAcceptedEvent.OutputObject>;
getEvent(key: 'ModeratorOfferCreated'): TypedContractEvent<ModeratorOfferCreatedEvent.InputTuple, ModeratorOfferCreatedEvent.OutputTuple, ModeratorOfferCreatedEvent.OutputObject>;
getEvent(key: 'ModeratorOfferDeclined'): TypedContractEvent<ModeratorOfferDeclinedEvent.InputTuple, ModeratorOfferDeclinedEvent.OutputTuple, ModeratorOfferDeclinedEvent.OutputObject>;
getEvent(key: 'ModeratorRecommended'): TypedContractEvent<ModeratorRecommendedEvent.InputTuple, ModeratorRecommendedEvent.OutputTuple, ModeratorRecommendedEvent.OutputObject>;
getEvent(key: 'ModeratorRemoved'): TypedContractEvent<ModeratorRemovedEvent.InputTuple, ModeratorRemovedEvent.OutputTuple, ModeratorRemovedEvent.OutputObject>;
getEvent(key: 'ModeratorResigned'): TypedContractEvent<ModeratorResignedEvent.InputTuple, ModeratorResignedEvent.OutputTuple, ModeratorResignedEvent.OutputObject>;
getEvent(key: 'PendingCommentApproved'): TypedContractEvent<PendingCommentApprovedEvent.InputTuple, PendingCommentApprovedEvent.OutputTuple, PendingCommentApprovedEvent.OutputObject>;
getEvent(key: 'PendingCommentRejected'): TypedContractEvent<PendingCommentRejectedEvent.InputTuple, PendingCommentRejectedEvent.OutputTuple, PendingCommentRejectedEvent.OutputObject>;
getEvent(key: 'PendingPostApproved'): TypedContractEvent<PendingPostApprovedEvent.InputTuple, PendingPostApprovedEvent.OutputTuple, PendingPostApprovedEvent.OutputObject>;
getEvent(key: 'PendingPostRejected'): TypedContractEvent<PendingPostRejectedEvent.InputTuple, PendingPostRejectedEvent.OutputTuple, PendingPostRejectedEvent.OutputObject>;
getEvent(key: 'PostCreated'): TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
getEvent(key: 'PostHidden'): TypedContractEvent<PostHiddenEvent.InputTuple, PostHiddenEvent.OutputTuple, PostHiddenEvent.OutputObject>;
getEvent(key: 'PostLocked'): TypedContractEvent<PostLockedEvent.InputTuple, PostLockedEvent.OutputTuple, PostLockedEvent.OutputObject>;
getEvent(key: 'PostRestored'): TypedContractEvent<PostRestoredEvent.InputTuple, PostRestoredEvent.OutputTuple, PostRestoredEvent.OutputObject>;
getEvent(key: 'PostSubmittedForReview'): TypedContractEvent<PostSubmittedForReviewEvent.InputTuple, PostSubmittedForReviewEvent.OutputTuple, PostSubmittedForReviewEvent.OutputObject>;
getEvent(key: 'PostUnlocked'): TypedContractEvent<PostUnlockedEvent.InputTuple, PostUnlockedEvent.OutputTuple, PostUnlockedEvent.OutputObject>;
getEvent(key: 'PostVoted'): TypedContractEvent<PostVotedEvent.InputTuple, PostVotedEvent.OutputTuple, PostVotedEvent.OutputObject>;
getEvent(key: 'RemoveModeratorProposalApproved'): TypedContractEvent<RemoveModeratorProposalApprovedEvent.InputTuple, RemoveModeratorProposalApprovedEvent.OutputTuple, RemoveModeratorProposalApprovedEvent.OutputObject>;
getEvent(key: 'RemoveModeratorProposalCreated'): TypedContractEvent<RemoveModeratorProposalCreatedEvent.InputTuple, RemoveModeratorProposalCreatedEvent.OutputTuple, RemoveModeratorProposalCreatedEvent.OutputObject>;
getEvent(key: 'RemoveModeratorProposalExecuted'): TypedContractEvent<RemoveModeratorProposalExecutedEvent.InputTuple, RemoveModeratorProposalExecutedEvent.OutputTuple, RemoveModeratorProposalExecutedEvent.OutputObject>;
getEvent(key: 'SubCommunityCreated'): TypedContractEvent<SubCommunityCreatedEvent.InputTuple, SubCommunityCreatedEvent.OutputTuple, SubCommunityCreatedEvent.OutputObject>;
getEvent(key: 'UserBanned'): TypedContractEvent<UserBannedEvent.InputTuple, UserBannedEvent.OutputTuple, UserBannedEvent.OutputObject>;
getEvent(key: 'UserUnbanned'): TypedContractEvent<UserUnbannedEvent.InputTuple, UserUnbannedEvent.OutputTuple, UserUnbannedEvent.OutputObject>;
getEvent(key: 'UsernameChanged'): TypedContractEvent<UsernameChangedEvent.InputTuple, UsernameChangedEvent.OutputTuple, UsernameChangedEvent.OutputObject>;
getEvent(key: 'UsernameRegistered'): TypedContractEvent<UsernameRegisteredEvent.InputTuple, UsernameRegisteredEvent.OutputTuple, UsernameRegisteredEvent.OutputObject>;

    filters: {
      
      'ActiveModeratorsUpdated(uint256,address,address,uint256)': TypedContractEvent<ActiveModeratorsUpdatedEvent.InputTuple, ActiveModeratorsUpdatedEvent.OutputTuple, ActiveModeratorsUpdatedEvent.OutputObject>;
      ActiveModeratorsUpdated: TypedContractEvent<ActiveModeratorsUpdatedEvent.InputTuple, ActiveModeratorsUpdatedEvent.OutputTuple, ActiveModeratorsUpdatedEvent.OutputObject>;
    

      'CommentCreated(uint256,uint256,uint256,address,string,string,uint256)': TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
      CommentCreated: TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
    

      'CommentHidden(uint256,uint256,uint256,address,uint256)': TypedContractEvent<CommentHiddenEvent.InputTuple, CommentHiddenEvent.OutputTuple, CommentHiddenEvent.OutputObject>;
      CommentHidden: TypedContractEvent<CommentHiddenEvent.InputTuple, CommentHiddenEvent.OutputTuple, CommentHiddenEvent.OutputObject>;
    

      'CommentSubmittedForReview(uint256,uint256,uint256,address,string,string,uint256)': TypedContractEvent<CommentSubmittedForReviewEvent.InputTuple, CommentSubmittedForReviewEvent.OutputTuple, CommentSubmittedForReviewEvent.OutputObject>;
      CommentSubmittedForReview: TypedContractEvent<CommentSubmittedForReviewEvent.InputTuple, CommentSubmittedForReviewEvent.OutputTuple, CommentSubmittedForReviewEvent.OutputObject>;
    

      'CommentsMerkleRootUpdated(uint256,uint256,bytes32,address,uint256)': TypedContractEvent<CommentsMerkleRootUpdatedEvent.InputTuple, CommentsMerkleRootUpdatedEvent.OutputTuple, CommentsMerkleRootUpdatedEvent.OutputObject>;
      CommentsMerkleRootUpdated: TypedContractEvent<CommentsMerkleRootUpdatedEvent.InputTuple, CommentsMerkleRootUpdatedEvent.OutputTuple, CommentsMerkleRootUpdatedEvent.OutputObject>;
    

      'CommunityCreated(uint256,address,string,string,string,uint256)': TypedContractEvent<CommunityCreatedEvent.InputTuple, CommunityCreatedEvent.OutputTuple, CommunityCreatedEvent.OutputObject>;
      CommunityCreated: TypedContractEvent<CommunityCreatedEvent.InputTuple, CommunityCreatedEvent.OutputTuple, CommunityCreatedEvent.OutputObject>;
    

      'CommunityJoined(uint256,address,uint256)': TypedContractEvent<CommunityJoinedEvent.InputTuple, CommunityJoinedEvent.OutputTuple, CommunityJoinedEvent.OutputObject>;
      CommunityJoined: TypedContractEvent<CommunityJoinedEvent.InputTuple, CommunityJoinedEvent.OutputTuple, CommunityJoinedEvent.OutputObject>;
    

      'CommunityLeft(uint256,address,uint256)': TypedContractEvent<CommunityLeftEvent.InputTuple, CommunityLeftEvent.OutputTuple, CommunityLeftEvent.OutputObject>;
      CommunityLeft: TypedContractEvent<CommunityLeftEvent.InputTuple, CommunityLeftEvent.OutputTuple, CommunityLeftEvent.OutputObject>;
    

      'CommunityMetadataUpdated(uint256,string,uint256)': TypedContractEvent<CommunityMetadataUpdatedEvent.InputTuple, CommunityMetadataUpdatedEvent.OutputTuple, CommunityMetadataUpdatedEvent.OutputObject>;
      CommunityMetadataUpdated: TypedContractEvent<CommunityMetadataUpdatedEvent.InputTuple, CommunityMetadataUpdatedEvent.OutputTuple, CommunityMetadataUpdatedEvent.OutputObject>;
    

      'ContentReported(uint256,uint256,uint8,address,string,uint256)': TypedContractEvent<ContentReportedEvent.InputTuple, ContentReportedEvent.OutputTuple, ContentReportedEvent.OutputObject>;
      ContentReported: TypedContractEvent<ContentReportedEvent.InputTuple, ContentReportedEvent.OutputTuple, ContentReportedEvent.OutputObject>;
    

      'ModeratorAdded(uint256,address,address,uint256)': TypedContractEvent<ModeratorAddedEvent.InputTuple, ModeratorAddedEvent.OutputTuple, ModeratorAddedEvent.OutputObject>;
      ModeratorAdded: TypedContractEvent<ModeratorAddedEvent.InputTuple, ModeratorAddedEvent.OutputTuple, ModeratorAddedEvent.OutputObject>;
    

      'ModeratorOfferAccepted(uint256,address,uint256)': TypedContractEvent<ModeratorOfferAcceptedEvent.InputTuple, ModeratorOfferAcceptedEvent.OutputTuple, ModeratorOfferAcceptedEvent.OutputObject>;
      ModeratorOfferAccepted: TypedContractEvent<ModeratorOfferAcceptedEvent.InputTuple, ModeratorOfferAcceptedEvent.OutputTuple, ModeratorOfferAcceptedEvent.OutputObject>;
    

      'ModeratorOfferCreated(uint256,address,uint256)': TypedContractEvent<ModeratorOfferCreatedEvent.InputTuple, ModeratorOfferCreatedEvent.OutputTuple, ModeratorOfferCreatedEvent.OutputObject>;
      ModeratorOfferCreated: TypedContractEvent<ModeratorOfferCreatedEvent.InputTuple, ModeratorOfferCreatedEvent.OutputTuple, ModeratorOfferCreatedEvent.OutputObject>;
    

      'ModeratorOfferDeclined(uint256,address,uint256)': TypedContractEvent<ModeratorOfferDeclinedEvent.InputTuple, ModeratorOfferDeclinedEvent.OutputTuple, ModeratorOfferDeclinedEvent.OutputObject>;
      ModeratorOfferDeclined: TypedContractEvent<ModeratorOfferDeclinedEvent.InputTuple, ModeratorOfferDeclinedEvent.OutputTuple, ModeratorOfferDeclinedEvent.OutputObject>;
    

      'ModeratorRecommended(uint256,address,address,uint256,uint256)': TypedContractEvent<ModeratorRecommendedEvent.InputTuple, ModeratorRecommendedEvent.OutputTuple, ModeratorRecommendedEvent.OutputObject>;
      ModeratorRecommended: TypedContractEvent<ModeratorRecommendedEvent.InputTuple, ModeratorRecommendedEvent.OutputTuple, ModeratorRecommendedEvent.OutputObject>;
    

      'ModeratorRemoved(uint256,address,address,uint256)': TypedContractEvent<ModeratorRemovedEvent.InputTuple, ModeratorRemovedEvent.OutputTuple, ModeratorRemovedEvent.OutputObject>;
      ModeratorRemoved: TypedContractEvent<ModeratorRemovedEvent.InputTuple, ModeratorRemovedEvent.OutputTuple, ModeratorRemovedEvent.OutputObject>;
    

      'ModeratorResigned(uint256,address,uint256)': TypedContractEvent<ModeratorResignedEvent.InputTuple, ModeratorResignedEvent.OutputTuple, ModeratorResignedEvent.OutputObject>;
      ModeratorResigned: TypedContractEvent<ModeratorResignedEvent.InputTuple, ModeratorResignedEvent.OutputTuple, ModeratorResignedEvent.OutputObject>;
    

      'PendingCommentApproved(uint256,uint256,uint256,address,uint256)': TypedContractEvent<PendingCommentApprovedEvent.InputTuple, PendingCommentApprovedEvent.OutputTuple, PendingCommentApprovedEvent.OutputObject>;
      PendingCommentApproved: TypedContractEvent<PendingCommentApprovedEvent.InputTuple, PendingCommentApprovedEvent.OutputTuple, PendingCommentApprovedEvent.OutputObject>;
    

      'PendingCommentRejected(uint256,uint256,uint256,address,uint256)': TypedContractEvent<PendingCommentRejectedEvent.InputTuple, PendingCommentRejectedEvent.OutputTuple, PendingCommentRejectedEvent.OutputObject>;
      PendingCommentRejected: TypedContractEvent<PendingCommentRejectedEvent.InputTuple, PendingCommentRejectedEvent.OutputTuple, PendingCommentRejectedEvent.OutputObject>;
    

      'PendingPostApproved(uint256,uint256,address,uint256)': TypedContractEvent<PendingPostApprovedEvent.InputTuple, PendingPostApprovedEvent.OutputTuple, PendingPostApprovedEvent.OutputObject>;
      PendingPostApproved: TypedContractEvent<PendingPostApprovedEvent.InputTuple, PendingPostApprovedEvent.OutputTuple, PendingPostApprovedEvent.OutputObject>;
    

      'PendingPostRejected(uint256,uint256,address,uint256)': TypedContractEvent<PendingPostRejectedEvent.InputTuple, PendingPostRejectedEvent.OutputTuple, PendingPostRejectedEvent.OutputObject>;
      PendingPostRejected: TypedContractEvent<PendingPostRejectedEvent.InputTuple, PendingPostRejectedEvent.OutputTuple, PendingPostRejectedEvent.OutputObject>;
    

      'PostCreated(uint256,uint256,address,string,string,string,uint256)': TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
      PostCreated: TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
    

      'PostHidden(uint256,uint256,address,uint256)': TypedContractEvent<PostHiddenEvent.InputTuple, PostHiddenEvent.OutputTuple, PostHiddenEvent.OutputObject>;
      PostHidden: TypedContractEvent<PostHiddenEvent.InputTuple, PostHiddenEvent.OutputTuple, PostHiddenEvent.OutputObject>;
    

      'PostLocked(uint256,uint256,address,uint256)': TypedContractEvent<PostLockedEvent.InputTuple, PostLockedEvent.OutputTuple, PostLockedEvent.OutputObject>;
      PostLocked: TypedContractEvent<PostLockedEvent.InputTuple, PostLockedEvent.OutputTuple, PostLockedEvent.OutputObject>;
    

      'PostRestored(uint256,uint256,address,uint256)': TypedContractEvent<PostRestoredEvent.InputTuple, PostRestoredEvent.OutputTuple, PostRestoredEvent.OutputObject>;
      PostRestored: TypedContractEvent<PostRestoredEvent.InputTuple, PostRestoredEvent.OutputTuple, PostRestoredEvent.OutputObject>;
    

      'PostSubmittedForReview(uint256,uint256,address,string,uint256)': TypedContractEvent<PostSubmittedForReviewEvent.InputTuple, PostSubmittedForReviewEvent.OutputTuple, PostSubmittedForReviewEvent.OutputObject>;
      PostSubmittedForReview: TypedContractEvent<PostSubmittedForReviewEvent.InputTuple, PostSubmittedForReviewEvent.OutputTuple, PostSubmittedForReviewEvent.OutputObject>;
    

      'PostUnlocked(uint256,uint256,address,uint256)': TypedContractEvent<PostUnlockedEvent.InputTuple, PostUnlockedEvent.OutputTuple, PostUnlockedEvent.OutputObject>;
      PostUnlocked: TypedContractEvent<PostUnlockedEvent.InputTuple, PostUnlockedEvent.OutputTuple, PostUnlockedEvent.OutputObject>;
    

      'PostVoted(uint256,uint256,address,int8,int256,uint256)': TypedContractEvent<PostVotedEvent.InputTuple, PostVotedEvent.OutputTuple, PostVotedEvent.OutputObject>;
      PostVoted: TypedContractEvent<PostVotedEvent.InputTuple, PostVotedEvent.OutputTuple, PostVotedEvent.OutputObject>;
    

      'RemoveModeratorProposalApproved(uint256,uint256,address,uint256,uint256)': TypedContractEvent<RemoveModeratorProposalApprovedEvent.InputTuple, RemoveModeratorProposalApprovedEvent.OutputTuple, RemoveModeratorProposalApprovedEvent.OutputObject>;
      RemoveModeratorProposalApproved: TypedContractEvent<RemoveModeratorProposalApprovedEvent.InputTuple, RemoveModeratorProposalApprovedEvent.OutputTuple, RemoveModeratorProposalApprovedEvent.OutputObject>;
    

      'RemoveModeratorProposalCreated(uint256,uint256,address,address,uint256,uint256)': TypedContractEvent<RemoveModeratorProposalCreatedEvent.InputTuple, RemoveModeratorProposalCreatedEvent.OutputTuple, RemoveModeratorProposalCreatedEvent.OutputObject>;
      RemoveModeratorProposalCreated: TypedContractEvent<RemoveModeratorProposalCreatedEvent.InputTuple, RemoveModeratorProposalCreatedEvent.OutputTuple, RemoveModeratorProposalCreatedEvent.OutputObject>;
    

      'RemoveModeratorProposalExecuted(uint256,uint256,address,uint256)': TypedContractEvent<RemoveModeratorProposalExecutedEvent.InputTuple, RemoveModeratorProposalExecutedEvent.OutputTuple, RemoveModeratorProposalExecutedEvent.OutputObject>;
      RemoveModeratorProposalExecuted: TypedContractEvent<RemoveModeratorProposalExecutedEvent.InputTuple, RemoveModeratorProposalExecutedEvent.OutputTuple, RemoveModeratorProposalExecutedEvent.OutputObject>;
    

      'SubCommunityCreated(uint256,uint256,address,string,string,string,uint256)': TypedContractEvent<SubCommunityCreatedEvent.InputTuple, SubCommunityCreatedEvent.OutputTuple, SubCommunityCreatedEvent.OutputObject>;
      SubCommunityCreated: TypedContractEvent<SubCommunityCreatedEvent.InputTuple, SubCommunityCreatedEvent.OutputTuple, SubCommunityCreatedEvent.OutputObject>;
    

      'UserBanned(uint256,address,address,uint256)': TypedContractEvent<UserBannedEvent.InputTuple, UserBannedEvent.OutputTuple, UserBannedEvent.OutputObject>;
      UserBanned: TypedContractEvent<UserBannedEvent.InputTuple, UserBannedEvent.OutputTuple, UserBannedEvent.OutputObject>;
    

      'UserUnbanned(uint256,address,address,uint256)': TypedContractEvent<UserUnbannedEvent.InputTuple, UserUnbannedEvent.OutputTuple, UserUnbannedEvent.OutputObject>;
      UserUnbanned: TypedContractEvent<UserUnbannedEvent.InputTuple, UserUnbannedEvent.OutputTuple, UserUnbannedEvent.OutputObject>;
    

      'UsernameChanged(address,string,string,uint256)': TypedContractEvent<UsernameChangedEvent.InputTuple, UsernameChangedEvent.OutputTuple, UsernameChangedEvent.OutputObject>;
      UsernameChanged: TypedContractEvent<UsernameChangedEvent.InputTuple, UsernameChangedEvent.OutputTuple, UsernameChangedEvent.OutputObject>;
    

      'UsernameRegistered(address,string,uint256)': TypedContractEvent<UsernameRegisteredEvent.InputTuple, UsernameRegisteredEvent.OutputTuple, UsernameRegisteredEvent.OutputObject>;
      UsernameRegistered: TypedContractEvent<UsernameRegisteredEvent.InputTuple, UsernameRegisteredEvent.OutputTuple, UsernameRegisteredEvent.OutputObject>;
    
    };
  }