/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DecentralizedForumInterface extends Interface {
    getFunction(nameOrSignature: "communityOfPost" | "createComment" | "createCommunity" | "createPost" | "getAllCommunityIds" | "getComment" | "getCommentCount" | "getCommentsByPost" | "getCommunity" | "getCommunityCount" | "getPost" | "getPostCount" | "getPostsByCommunity" | "isMember" | "isUserMemberOfCommunity" | "joinCommunity"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CommentCreated" | "CommunityCreated" | "CommunityJoined" | "PostCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'communityOfPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createComment', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'createCommunity', values: [string, string]): string;
encodeFunctionData(functionFragment: 'createPost', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getAllCommunityIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getComment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCommentsByPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommunityCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPostCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPostsByCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isMember', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isUserMemberOfCommunity', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'joinCommunity', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'communityOfPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCommunityIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommentsByPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommunityCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPostCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPostsByCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUserMemberOfCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinCommunity', data: BytesLike): Result;
  }

  
    export namespace CommentCreatedEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, author: AddressLike, contentCID: string, createdAt: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, author: string, contentCID: string, createdAt: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, author: string, contentCID: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityCreatedEvent {
      export type InputTuple = [communityId: BigNumberish, creator: AddressLike, name: string, metadataCID: string, createdAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, creator: string, name: string, metadataCID: string, createdAt: bigint];
      export interface OutputObject {communityId: bigint, creator: string, name: string, metadataCID: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommunityJoinedEvent {
      export type InputTuple = [communityId: BigNumberish, member: AddressLike, joinedAt: BigNumberish];
      export type OutputTuple = [communityId: bigint, member: string, joinedAt: bigint];
      export interface OutputObject {communityId: bigint, member: string, joinedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostCreatedEvent {
      export type InputTuple = [postId: BigNumberish, communityId: BigNumberish, author: AddressLike, contentCID: string, createdAt: BigNumberish];
      export type OutputTuple = [postId: bigint, communityId: bigint, author: string, contentCID: string, createdAt: bigint];
      export interface OutputObject {postId: bigint, communityId: bigint, author: string, contentCID: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DecentralizedForum extends BaseContract {
    
    connect(runner?: ContractRunner | null): DecentralizedForum;
    waitForDeployment(): Promise<this>;

    interface: DecentralizedForumInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    communityOfPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createComment: TypedContractMethod<
      [postId: BigNumberish, contentCID: string, ],
      [void],
      'nonpayable'
    >
    

    
    createCommunity: TypedContractMethod<
      [name: string, metadataCID: string, ],
      [void],
      'nonpayable'
    >
    

    
    createPost: TypedContractMethod<
      [communityId: BigNumberish, contentCID: string, ],
      [void],
      'nonpayable'
    >
    

    
    getAllCommunityIds: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getComment: TypedContractMethod<
      [commentId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean] & {id: bigint, postId: bigint, author: string, contentCID: string, createdAt: bigint, exists: boolean }],
      'view'
    >
    

    
    getCommentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCommentsByPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean] & {id: bigint, name: string, creator: string, metadataCID: string, createdAt: bigint, membersCount: bigint, exists: boolean }],
      'view'
    >
    

    
    getCommunityCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPost: TypedContractMethod<
      [postId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean] & {id: bigint, communityId: bigint, author: string, contentCID: string, createdAt: bigint, exists: boolean }],
      'view'
    >
    

    
    getPostCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPostsByCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    isMember: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUserMemberOfCommunity: TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    joinCommunity: TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'communityOfPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createComment'): TypedContractMethod<
      [postId: BigNumberish, contentCID: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createCommunity'): TypedContractMethod<
      [name: string, metadataCID: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPost'): TypedContractMethod<
      [communityId: BigNumberish, contentCID: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllCommunityIds'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getComment'): TypedContractMethod<
      [commentId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean] & {id: bigint, postId: bigint, author: string, contentCID: string, createdAt: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getCommentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCommentsByPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean] & {id: bigint, name: string, creator: string, metadataCID: string, createdAt: bigint, membersCount: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getCommunityCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPost'): TypedContractMethod<
      [postId: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, boolean] & {id: bigint, communityId: bigint, author: string, contentCID: string, createdAt: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getPostCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPostsByCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isMember'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUserMemberOfCommunity'): TypedContractMethod<
      [communityId: BigNumberish, user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'joinCommunity'): TypedContractMethod<
      [communityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CommentCreated'): TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
getEvent(key: 'CommunityCreated'): TypedContractEvent<CommunityCreatedEvent.InputTuple, CommunityCreatedEvent.OutputTuple, CommunityCreatedEvent.OutputObject>;
getEvent(key: 'CommunityJoined'): TypedContractEvent<CommunityJoinedEvent.InputTuple, CommunityJoinedEvent.OutputTuple, CommunityJoinedEvent.OutputObject>;
getEvent(key: 'PostCreated'): TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;

    filters: {
      
      'CommentCreated(uint256,uint256,address,string,uint256)': TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
      CommentCreated: TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
    

      'CommunityCreated(uint256,address,string,string,uint256)': TypedContractEvent<CommunityCreatedEvent.InputTuple, CommunityCreatedEvent.OutputTuple, CommunityCreatedEvent.OutputObject>;
      CommunityCreated: TypedContractEvent<CommunityCreatedEvent.InputTuple, CommunityCreatedEvent.OutputTuple, CommunityCreatedEvent.OutputObject>;
    

      'CommunityJoined(uint256,address,uint256)': TypedContractEvent<CommunityJoinedEvent.InputTuple, CommunityJoinedEvent.OutputTuple, CommunityJoinedEvent.OutputObject>;
      CommunityJoined: TypedContractEvent<CommunityJoinedEvent.InputTuple, CommunityJoinedEvent.OutputTuple, CommunityJoinedEvent.OutputObject>;
    

      'PostCreated(uint256,uint256,address,string,uint256)': TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
      PostCreated: TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
    
    };
  }