/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as forumInterfacesSol from './ForumInterfaces.sol/index.js';
export type { forumInterfacesSol };
import type * as mainContractSol from './mainContract.sol/index.js';
export type { mainContractSol };
export type { ForumModeration } from './ForumModeration.js';
export type { UsernameRegistry } from './UsernameRegistry.js';
export * as factories from './factories/index.js';
export type { IDecentralizedForum } from './ForumInterfaces.sol/IDecentralizedForum.js';
export { IDecentralizedForum__factory } from './factories/ForumInterfaces.sol/IDecentralizedForum__factory.js';
export type { IForumModeration } from './ForumInterfaces.sol/IForumModeration.js';
export { IForumModeration__factory } from './factories/ForumInterfaces.sol/IForumModeration__factory.js';
export type { DecentralizedForum } from './mainContract.sol/DecentralizedForum.js';
export { DecentralizedForum__factory } from './factories/mainContract.sol/DecentralizedForum__factory.js';
export { ForumModeration__factory } from './factories/ForumModeration__factory.js';
export { UsernameRegistry__factory } from './factories/UsernameRegistry__factory.js';