/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DecentralizedForum } from './DecentralizedForum.js';
export * as factories from './factories/index.js';
export { DecentralizedForum__factory } from './factories/DecentralizedForum__factory.js';