/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as forumInterfacesSol from './ForumInterfaces.sol/index.js';
export * as mainContractSol from './mainContract.sol/index.js';
export { ForumModeration__factory } from './ForumModeration__factory.js';
export { UsernameRegistry__factory } from './UsernameRegistry__factory.js';